# Generated by Django 3.2.3 on 2022-01-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20220103_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='avatar/default avatar.jpg', null=True, upload_to='avatar', verbose_name='Ảnh đại diện'),
        ),
    ]
