# Generated by Django 4.0 on 2022-01-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_voucher_uservoucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
