# Generated by Django 4.0 on 2022-01-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_voucher_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='usage_limit_field',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='usage_no_field',
        ),
        migrations.AddField(
            model_name='voucher',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Có hoạt động?'),
        ),
    ]
