# Generated by Django 4.0 on 2022-01-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_remove_voucher_usage_limit_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Mã giảm giá'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount',
            field=models.FloatField(default=0, verbose_name='Giảm giá - số là trừ tiền,dạng thập phân là giảm %'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Còn sử dụng được không'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='type',
            field=models.IntegerField(verbose_name='Thể loại - 0 là trừ tiền hàng, 1 là freeship'),
        ),
    ]
